// Mock product data – replace with Supabase queries once DB is set up

export const mockProducts = [
  // ── Pasupu-Kumkuma Standard ──────────────────────────────────────────────
  {
    id: 'pk-1',
    name: 'Pasupu Kumkuma Couple Set',
    category: 'pasupu',
    type: 'standard',
    price: 120,
    unit: 'set',
    description: 'Traditional pasupu kumkuma set beautifully presented for couples — perfect for weddings and celebrations.',
    image_url: '/images/pasupukumkuma-couple.jpeg',
    variants: ['Small', 'Medium', 'Large'],
  },
  {
    id: 'pk-2',
    name: 'Pasupu Kumkuma Bag Set',
    category: 'pasupu',
    type: 'standard',
    price: 180,
    unit: 'set',
    description: 'Elegant pasupu kumkuma set packed in a decorative bag, ideal as a return gift.',
    image_url: '/images/pasupukumkuma-bag.jpeg',
    variants: ['Small', 'Medium', 'Large'],
  },
  {
    id: 'pk-3',
    name: 'Krishna Theme Pasupu Set',
    category: 'pasupu',
    type: 'standard',
    price: 250,
    unit: 'set',
    description: 'Devotional Krishna-themed pasupu kumkuma set, perfect for pooja and religious occasions.',
    image_url: '/images/pasupukumkuma-krishna.jpeg',
    variants: ['Small', 'Medium'],
  },
  {
    id: 'pk-4',
    name: 'House Opening Pasupu Set',
    category: 'pasupu',
    type: 'standard',
    price: 150,
    unit: 'set',
    description: 'Auspicious pasupu kumkuma set specially curated for housewarming (griha pravesham) ceremonies.',
    image_url: '/images/pasupukumkuma-houseopening.jpeg',
    variants: ['Small', 'Medium', 'Large'],
  },

  // ── Pasupu-Kumkuma Customization ─────────────────────────────────────────
  {
    id: 'pk-c1',
    name: 'Custom Design Set',
    category: 'pasupu',
    type: 'customization',
    price: null,
    description: 'Fully customized pasupu kumkuma set — choose your theme, colors, and design.',
    image_url: '/images/pasupukkumkuma-design.jpeg',
  },
  {
    id: 'pk-c2',
    name: 'Wedding Theme',
    category: 'pasupu',
    type: 'customization',
    price: null,
    description: 'Elegant wedding-themed customized pasupu kumkuma set for the perfect return gift.',
    image_url: '/images/pasupukumkuma-couple.jpeg',
  },
  {
    id: 'pk-c3',
    name: 'Krishna / Devotional Theme',
    category: 'pasupu',
    type: 'customization',
    price: null,
    description: 'Devotional Krishna-themed customized set for religious functions and festivals.',
    image_url: '/images/pasupukumkuma-krishna.jpeg',
  },
  {
    id: 'pk-c4',
    name: 'Housewarming Theme',
    category: 'pasupu',
    type: 'customization',
    price: null,
    description: 'Auspicious housewarming (griha pravesham) themed customized pasupu kumkuma set.',
    image_url: '/images/pasupukumkuma-houseopening.jpeg',
  },
  {
    id: 'pk-c5',
    name: 'Bag & Pouch Theme',
    category: 'pasupu',
    type: 'customization',
    price: null,
    description: 'Customized pasupu kumkuma set presented in a beautifully designed bag or pouch.',
    image_url: '/images/pasupukumkuma-bag.jpeg',
  },
  {
    id: 'pk-c6',
    name: 'Fully Custom Design',
    category: 'pasupu',
    type: 'customization',
    price: null,
    description: 'Send us your idea and we\'ll create a completely unique design just for you.',
    image_url: '/images/pasupukkumkuma-design.jpeg',
  },

  // ── Return Gifts ─────────────────────────────────────────────────────────
  {
    id: 'rg-1',
    name: 'Brass Diya Set',
    category: 'gifts',
    type: 'standard',
    price: 199,
    unit: 'piece',
    description: 'Handcrafted brass diya set, ideal as return gift for pooja and festivals.',
    image_url: 'https://images.unsplash.com/photo-1574169208507-84376144848b?w=400&q=80',
    variants: ['Single', 'Set of 2', 'Set of 4'],
  },
  {
    id: 'rg-2',
    name: 'Coconut Shell Bowl',
    category: 'gifts',
    type: 'standard',
    price: 149,
    unit: 'piece',
    description: 'Eco-friendly coconut shell bowl, a unique and sustainable return gift.',
    image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80',
    variants: ['Small', 'Medium'],
  },
  {
    id: 'rg-3',
    name: 'Terracotta Planter',
    category: 'gifts',
    type: 'standard',
    price: 129,
    unit: 'piece',
    description: 'Traditional terracotta planter with seeds, a thoughtful return gift.',
    image_url: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&q=80',
    variants: ['Small', 'Medium', 'Large'],
  },
  {
    id: 'rg-4',
    name: 'Wooden Keychain Set',
    category: 'gifts',
    type: 'standard',
    price: 89,
    unit: 'piece',
    description: 'Handcrafted wooden keychain with traditional motifs.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    variants: ['Pack of 5', 'Pack of 10', 'Pack of 20'],
  },
  {
    id: 'rg-5',
    name: 'Agarbatti Gift Set',
    category: 'gifts',
    type: 'standard',
    price: 175,
    unit: 'set',
    description: 'Premium agarbatti set with holder, perfect for gifting.',
    image_url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80',
    variants: ['Small', 'Medium', 'Large'],
  },
  {
    id: 'rg-6',
    name: 'Copper Tumbler',
    category: 'gifts',
    type: 'standard',
    price: 299,
    unit: 'piece',
    description: 'Pure copper tumbler, a healthy and traditional return gift.',
    image_url: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80',
    variants: ['Small', 'Medium'],
  },

  // ── Return Bags ──────────────────────────────────────────────────────────
  {
    id: 'rb-1',
    name: 'Jute Return Bag',
    category: 'bags',
    type: 'standard',
    price: 79,
    unit: 'piece',
    description: 'Eco-friendly jute bag with traditional print, perfect for return gifts.',
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
    variants: ['Small', 'Medium', 'Large'],
  },
  {
    id: 'rb-2',
    name: 'Silk Potli Bag',
    category: 'bags',
    type: 'standard',
    price: 149,
    unit: 'piece',
    description: 'Beautiful silk potli bag with golden embroidery for weddings and festivals.',
    image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&q=80',
    variants: ['Small', 'Medium'],
  },
  {
    id: 'rb-3',
    name: 'Cotton Tote Bag',
    category: 'bags',
    type: 'standard',
    price: 99,
    unit: 'piece',
    description: 'Reusable cotton tote bag with traditional block print design.',
    image_url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400&q=80',
    variants: ['Small', 'Medium', 'Large'],
  },
  {
    id: 'rb-4',
    name: 'Velvet Gift Pouch',
    category: 'bags',
    type: 'standard',
    price: 119,
    unit: 'piece',
    description: 'Luxurious velvet pouch with drawstring, ideal for premium return gifts.',
    image_url: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400&q=80',
    variants: ['Small', 'Medium', 'Large'],
  },
  {
    id: 'rb-5',
    name: 'Paper Gift Bag',
    category: 'bags',
    type: 'standard',
    price: 49,
    unit: 'piece',
    description: 'Elegant paper gift bag with traditional motif print.',
    image_url: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=400&q=80',
    variants: ['Small', 'Medium', 'Large'],
  },
  {
    id: 'rb-6',
    name: 'Embroidered Cloth Bag',
    category: 'bags',
    type: 'standard',
    price: 189,
    unit: 'piece',
    description: 'Hand-embroidered cloth bag with intricate traditional patterns.',
    image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&q=80',
    variants: ['Small', 'Medium'],
  },
]

export const categories = [
  {
    id: 'pasupu',
    name: 'Pasupu-Kumkuma',
    description: 'Traditional turmeric & kumkuma sets for every occasion',
    image_url: '/images/pasupukumkuma-couple.jpeg',
    hasTabs: true,
    path: '/category/pasupu',
  },
  {
    id: 'gifts',
    name: 'Return Gifts',
    description: 'Thoughtful traditional gifts for your guests',
    image_url: 'https://images.unsplash.com/photo-1574169208507-84376144848b?w=600&q=80',
    hasTabs: false,
    path: '/category/gifts',
  },
  {
    id: 'bags',
    name: 'Return Bags',
    description: 'Beautiful bags to present your return gifts',
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    hasTabs: false,
    path: '/category/bags',
  },
]
